services:
  backend:
    image: ghcr.io/osmitalia/estratti_osm_italia-backend:main
    build: backend
    #command: anacron -dfn # force run
    restart: always
    volumes:
    - ./data/input:/data/input
    - ./data/output:/data/output
    - ./data/log:/var/log/estratti
  webapp:
    image: ghcr.io/osmitalia/estratti_osm_italia-webapp:main
    build: webapp
    ports:
    - 8000:80
    volumes:
    - ./data/output:/srv/estratti/output
