services:
  backend:
    build: backend
    #command: anacron -dfn # force run
    restart: always
    volumes:
    - ./data:/data
    - ./data/log:/var/log/estratti
  webapp:
    build: webapp
    ports:
    - 8000:80
    volumes:
    - ./data/output:/srv/estratti/output
